#%RAML 1.0 Library
usage: Library of data types

types:
  customers-details: !include /dataTypes/customers.raml
  customer-details: !include /dataTypes/customer-by-id.raml
  customer-details-only: !include /dataTypes/customer.raml
  id-only: !include /dataTypes/id.raml