#%RAML 1.0 Library
usage: Library of data types

types:
  accounts-details: !include /dataTypes/accounts.raml
  account-details: !include /dataTypes/account-by-id.raml
  account-details-only: !include /dataTypes/account.raml
  id-only: !include /dataTypes/id.raml