#%RAML 1.0 Library
usage: Library of data types

types:
  clients-details: !include /dataTypes/clients.raml
  client-details: !include /dataTypes/client-by-id.raml
  client-details-only: !include /dataTypes/client.raml
  id-only: !include /dataTypes/id.raml