#%RAML 1.0 DataType
usage: Customer personal information.

properties:
  name:
    type: string
    example: 'Harry Potter'
    maxLength: 100
  phone:
    type: string
    example: '+6402175315964'
    maxLength: 50
  email:
    type: string
    example: 'wizard@harrypotter.com'
  born:
    type: string
    example: 'Monday, 26 Janurary, 1981'
  gender:
    type: string
    enum:
      - Male
      - Female
    example: 'Male'